#!/usr/bin/env python3
"""Turn the shared ACL case set into a C header.

The C test would otherwise need a JSON parser just to read its fixtures, which
would drag jansson into a test that is meant to depend on nothing but glib.
Generating a header keeps the C side dependency-free while still driving it
from the one authoritative case file.

This emits two blocks:

  * ``cf_acl_cases`` -- the rule-resolution cases that drive cf_acl_resolve.
    These have always been here.
  * ``cf_acl_authority_states`` -- the three-state authority contract added
    in v2 of the fixture (SEC-02). The C resolver never classifies these --
    that lives in cf-acl.c, which needs the full seafile build -- but the
    fixture itself is a contract every consumer agrees on, so the C harness
    asserts the canonical state names and verdicts are present and
    self-consistent. The classification test is deferred to the Linux CI
    build per plan 01-02's macOS limitation note.

Usage: gen-cases.py path/to/acl-cases.json > cf-acl-cases.h
"""

import json
import sys


def c_string(value):
    if value is None:
        return 'NULL'
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return '"%s"' % escaped


def emit_rule_cases(data, out):
    out.write('/* Generated by tests/cf-acl/gen-cases.py. Do not edit.\n')
    out.write(' * Source: cloudfile-docker/docs/acl-cases.json (version %d)\n'
              % data['version'])
    out.write(' */\n\n')
    out.write('#ifndef CF_ACL_CASES_H\n#define CF_ACL_CASES_H\n\n')

    out.write('typedef struct { const char *path; const char *subject_type;\n'
              '    const char *subject; const char *permission; int inherit;\n'
              '} CaseRule;\n\n')
    out.write('typedef struct { const char *path; const char *native;\n'
              '    const char *expect; } CaseCheck;\n\n')
    out.write('typedef struct { const char *name; const char *user;\n'
              '    const char **groups; const char **depts;\n'
              '    const CaseRule *rules; int n_rules;\n'
              '    const CaseCheck *checks; int n_checks; } Case;\n\n')

    for index, case in enumerate(data['cases']):
        subjects = case['subjects']

        groups = list(subjects.get('groups') or ())
        out.write('static const char *case%d_groups[] = { %s NULL };\n'
                  % (index, ''.join('%s, ' % c_string(g) for g in groups)))

        depts = list(subjects.get('depts') or ())
        out.write('static const char *case%d_depts[] = { %s NULL };\n'
                  % (index, ''.join('%s, ' % c_string(d) for d in depts)))

        out.write('static const CaseRule case%d_rules[] = {\n' % index)
        for rule in case['rules']:
            out.write('    { %s, %s, %s, %s, %d },\n' % (
                c_string(rule['path']), c_string(rule['subject_type']),
                c_string(rule['subject']), c_string(rule['permission']),
                int(rule['inherit'])))
        out.write('    { NULL, NULL, NULL, NULL, 0 }\n};\n')

        out.write('static const CaseCheck case%d_checks[] = {\n' % index)
        for check in case['checks']:
            out.write('    { %s, %s, %s },\n' % (
                c_string(check['path']), c_string(check['native']),
                c_string(check['expect'])))
        out.write('};\n\n')

    out.write('static const Case cf_acl_cases[] = {\n')
    for index, case in enumerate(data['cases']):
        out.write('    { %s, %s, case%d_groups, case%d_depts,\n'
                  '      case%d_rules, %d, case%d_checks, %d },\n' % (
                      c_string(case['name']),
                      c_string(case['subjects']['user']),
                      index, index, index, len(case['rules']),
                      index, len(case['checks'])))
    out.write('};\n\n')
    out.write('#define CF_ACL_N_CASES %d\n\n' % len(data['cases']))


def emit_authority_states(data, out):
    """Emit the three-state authority contract from the v2 fixture.

    Each state becomes a row naming (name, feature_enabled, verdict). The C
    harness asserts the canonical states are present and that no
    feature-enabled state is allowed to classify as passthrough -- the single
    invariant that keeps an active authority outage from being silently
    treated as "no restriction".
    """
    block = data.get('authority_states') or {}
    states = block.get('states') or []

    out.write('/* The three-state authority contract (SEC-02).\n')
    out.write(' * Source: cloudfile-docker/docs/acl-cases.json::authority_states\n')
    out.write(' * Classifier lives in cf-acl.c (full build); this header only\n')
    out.write(' * carries the fixture so the dependency-free harness can assert\n')
    out.write(' * the contract is self-consistent. */\n\n')

    out.write('typedef struct { const char *name; int feature_enabled;\n'
              '    const char *verdict; } AuthorityState;\n\n')

    if not states:
        out.write('static const AuthorityState cf_acl_authority_states[] = {\n')
        out.write('    { NULL, 0, NULL }\n};\n')
        out.write('#define CF_ACL_N_AUTHORITY_STATES 0\n\n')
        out.write('#endif /* CF_ACL_CASES_H */\n')
        return

    for state in states:
        out.write('static const AuthorityState authority_state_%s = { %s, %d, %s };\n'
                  % (state['name'].replace('-', '_'),
                     c_string(state['name']),
                     1 if state.get('feature_enabled') else 0,
                     c_string(state.get('verdict'))))

    out.write('\nstatic const AuthorityState cf_acl_authority_states[] = {\n')
    for state in states:
        out.write('    authority_state_%s,\n' % state['name'].replace('-', '_'))
    out.write('    { NULL, 0, NULL }\n};\n\n')
    out.write('#define CF_ACL_N_AUTHORITY_STATES %d\n\n' % len(states))

    revisions = block.get('revision_monotonicity') or []
    out.write('/* revision monotonicity: (op, before, after) triples. The C\n')
    out.write(' * classifier persists this counter; the harness only asserts\n')
    out.write(' * the sequence is strictly increasing. */\n')
    out.write('typedef struct { const char *op; int before; int after; } '
              'RevisionStep;\n\n')
    out.write('static const RevisionStep cf_acl_revision_steps[] = {\n')
    for step in revisions:
        before = step.get('before')
        out.write('    { %s, %d, %d },\n' % (
            c_string(step.get('op')),
            -1 if before is None else int(before),
            int(step.get('after') or 0)))
    out.write('    { NULL, 0, 0 }\n};\n')
    out.write('#define CF_ACL_N_REVISION_STEPS %d\n\n' % len(revisions))
    out.write('#define CF_ACL_UNKNOWN_STATE_VERDICT %s\n\n'
              % c_string(block.get('unknown_state_verdict')))

    out.write('#endif /* CF_ACL_CASES_H */\n')


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        return 2

    with open(sys.argv[1], encoding='utf-8') as fp:
        data = json.load(fp)

    out = sys.stdout
    emit_rule_cases(data, out)
    emit_authority_states(data, out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
