#!/usr/bin/env python3
"""Turn the shared ACL case set into a C header.

The C test would otherwise need a JSON parser just to read its fixtures, which
would drag jansson into a test that is meant to depend on nothing but glib.
Generating a header keeps the C side dependency-free while still driving it
from the one authoritative case file.

Usage: gen-cases.py path/to/acl-cases.json > cf-acl-cases.h
"""

import json
import sys


def c_string(value):
    if value is None:
        return 'NULL'
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return '"%s"' % escaped


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        return 2

    with open(sys.argv[1], encoding='utf-8') as fp:
        data = json.load(fp)

    out = sys.stdout
    out.write('/* Generated by tests/cf-acl/gen-cases.py. Do not edit.\n')
    out.write(' * Source: cloudfile-docker/docs/acl-cases.json (version %d)\n'
              % data['version'])
    out.write(' */\n\n')
    out.write('#ifndef CF_ACL_CASES_H\n#define CF_ACL_CASES_H\n\n')

    out.write('typedef struct { const char *path; const char *subject_type;\n'
              '    const char *subject; const char *permission; int inherit;\n'
              '} CaseRule;\n\n')
    out.write('typedef struct { const char *path; const char *native;\n'
              '    const char *expect; } CaseCheck;\n\n')
    out.write('typedef struct { const char *name; const char *user;\n'
              '    const char **groups; const char **depts;\n'
              '    const CaseRule *rules; int n_rules;\n'
              '    const CaseCheck *checks; int n_checks; } Case;\n\n')

    for index, case in enumerate(data['cases']):
        subjects = case['subjects']

        groups = list(subjects.get('groups') or ())
        out.write('static const char *case%d_groups[] = { %s NULL };\n'
                  % (index, ''.join('%s, ' % c_string(g) for g in groups)))

        depts = list(subjects.get('depts') or ())
        out.write('static const char *case%d_depts[] = { %s NULL };\n'
                  % (index, ''.join('%s, ' % c_string(d) for d in depts)))

        out.write('static const CaseRule case%d_rules[] = {\n' % index)
        for rule in case['rules']:
            out.write('    { %s, %s, %s, %s, %d },\n' % (
                c_string(rule['path']), c_string(rule['subject_type']),
                c_string(rule['subject']), c_string(rule['permission']),
                int(rule['inherit'])))
        out.write('    { NULL, NULL, NULL, NULL, 0 }\n};\n')

        out.write('static const CaseCheck case%d_checks[] = {\n' % index)
        for check in case['checks']:
            out.write('    { %s, %s, %s },\n' % (
                c_string(check['path']), c_string(check['native']),
                c_string(check['expect'])))
        out.write('};\n\n')

    out.write('static const Case cf_acl_cases[] = {\n')
    for index, case in enumerate(data['cases']):
        out.write('    { %s, %s, case%d_groups, case%d_depts,\n'
                  '      case%d_rules, %d, case%d_checks, %d },\n' % (
                      c_string(case['name']),
                      c_string(case['subjects']['user']),
                      index, index, index, len(case['rules']),
                      index, len(case['checks'])))
    out.write('};\n\n')
    out.write('#define CF_ACL_N_CASES %d\n\n' % len(data['cases']))
    out.write('#endif /* CF_ACL_CASES_H */\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
