#!/usr/bin/env python3
"""Turn the shared write-lifecycle case set into a C header.

The C test would otherwise need a JSON parser just to read its fixtures, which
would drag jansson into a test that is meant to depend on nothing but glib --
the same reason tests/cf-acl generates its own header. Generating keeps the C
side dependency-free while still driving it from the one authoritative file.

Usage: gen-cases.py path/to/fileop-cases.json > cf-fileop-cases.h
"""

import json
import sys


def c_string(value):
    if value is None:
        return 'NULL'
    escaped = (value.replace('\\', '\\\\')
                    .replace('"', '\\"'))
    # Non-ASCII paths are in the case set on purpose (the "no Unicode
    # normalization" cases). Escape them byte-wise so the generated header is
    # pure ASCII and cannot be re-normalized by an editor on its way through.
    out = []
    for byte in escaped.encode('utf-8'):
        if 0x20 <= byte < 0x7f:
            out.append(chr(byte))
        else:
            out.append('\\x%02x""' % byte)
    return '"%s"' % ''.join(out)


VERDICTS = {'allow': 0, 'refuse': 1, 'none': 2}
PREPARES = {'allow': 0, 'refuse': 1, 'inactive': 2}


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        return 2

    with open(sys.argv[1], encoding='utf-8') as fp:
        data = json.load(fp)

    out = sys.stdout
    out.write('/* Generated by tests/cf-fileop/gen-cases.py. Do not edit.\n')
    out.write(' * Source: cloudfile-docker/docs/fileop-cases.json (version %d)\n'
              % data['version'])
    out.write(' */\n\n')
    out.write('#ifndef CF_FILEOP_CASES_H\n#define CF_FILEOP_CASES_H\n\n')

    # --- normalize -------------------------------------------------------
    out.write('typedef struct { const char *name; const char *dir;\n'
              '    const char *entry; const char *expect; } NormalizeCase;\n\n')
    cases = data['normalize']['cases']
    out.write('static const NormalizeCase cf_normalize_cases[] = {\n')
    for case in cases:
        out.write('    { %s, %s, %s, %s },\n' % (
            c_string(case['name']), c_string(case['dir']),
            c_string(case['entry']), c_string(case['expect'])))
    out.write('};\n')
    out.write('#define CF_N_NORMALIZE_CASES %d\n\n' % len(cases))

    # --- operations ------------------------------------------------------
    out.write('typedef struct { const char *op; int valid; int source;\n'
              '    int pathless; int subject_is_root; } OperationCase;\n\n')
    cases = data['operations']['cases']
    out.write('static const OperationCase cf_operation_cases[] = {\n')
    for case in cases:
        out.write('    { %s, %d, %d, %d, %d },\n' % (
            c_string(case['op']), int(case['valid']), int(case['source']),
            int(case['pathless']), int(case['subject_is_root'])))
    out.write('};\n')
    out.write('#define CF_N_OPERATION_CASES %d\n\n' % len(cases))

    # --- has_component ---------------------------------------------------
    out.write('typedef struct { const char *name; const char *path;\n'
              '    const char *component; int expect; } ComponentCase;\n\n')
    cases = data['has_component']['cases']
    out.write('static const ComponentCase cf_component_cases[] = {\n')
    for case in cases:
        out.write('    { %s, %s, %s, %d },\n' % (
            c_string(case['name']), c_string(case['path']),
            c_string(case['component']), int(case['expect'])))
    out.write('};\n')
    out.write('#define CF_N_COMPONENT_CASES %d\n\n' % len(cases))

    # --- dispatch --------------------------------------------------------
    out.write('typedef struct { const char *name; const int *verdicts;\n'
              '    int n_verdicts; int expect_allowed; int expect_ran;\n'
              '} DispatchCase;\n\n')
    cases = data['dispatch']['cases']
    for index, case in enumerate(cases):
        verdicts = [VERDICTS[v] for v in case['verdicts']]
        out.write('static const int dispatch%d_verdicts[] = { %s0 };\n'
                  % (index, ''.join('%d, ' % v for v in verdicts)))
    out.write('static const DispatchCase cf_dispatch_cases[] = {\n')
    for index, case in enumerate(cases):
        out.write('    { %s, dispatch%d_verdicts, %d, %d, %d },\n' % (
            c_string(case['name']), index, len(case['verdicts']),
            int(case['expect_allowed']), int(case['expect_ran'])))
    out.write('};\n')
    out.write('#define CF_N_DISPATCH_CASES %d\n\n' % len(cases))

    # --- facts -----------------------------------------------------------
    out.write('typedef struct { const char *name; int prepare;\n'
              '    int commit_attempts; int succeeded;\n'
              '    int expect_committed; int expect_aborted; } FactCase;\n\n')
    cases = data['facts']['cases']
    out.write('static const FactCase cf_fact_cases[] = {\n')
    for case in cases:
        out.write('    { %s, %d, %d, %d, %d, %d },\n' % (
            c_string(case['name']), PREPARES[case['prepare']],
            case['commit_attempts'], int(case['succeeded']),
            case['expect_committed'], case['expect_aborted']))
    out.write('};\n')
    out.write('#define CF_N_FACT_CASES %d\n\n' % len(cases))

    out.write('#endif /* CF_FILEOP_CASES_H */\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
